name: .NET

on:
  push:
    branches: [ main ]
    paths: apis/poi/**
  pull_request:
    branches: [ main ]

build:
  stage: build
  
jobs:
  build:
    variables:
    build_path: "openhack-devops-team5/openhack-devops-team5/apis/poi"
    runs-on: ubuntu-latest
  script:
    - "cd $build_path"
  steps:
  - uses: actions/checkout@v2
  - name: Setup .NET
    uses: actions/setup-dotnet@v1
    with:
      dotnet-version: 5.0.x
  - name: Restore dependencies
    run: dotnet restore
  - name: Build
    run: dotnet build --no-restore
  - name: Test
    run: dotnet test --no-build --verbosity normal