name: Docker Image CI

on:
  workflow_dispatch:
 # push:
 #  branches: [ main ]
  # pull_request:
  #  branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      # run: docker build apis/poi/web --file apis/poi/web/Dockerfile --tag my-image-name:$(date +%s)
      run: docker build apis/poi/web --file apis/poi/web/Dockerfile --tag ${{ secrets.ACR_LOGIN_SERVER }}/devopsoh/api-poi:${{ github.run_number }}
    - name: Login to the Container Registry  
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Push image
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/devopsoh/api-poi:${{ github.run_number }}
    - name: Deploy to Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhacktch9q931poi'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_STAGING }}
        images: ${{ secrets.ACR_LOGIN_SERVER }}/devopsoh/api-poi:${{ github.run_number }}
        slot-name: 'staging'
        
    - name: GET URL Health Check
      # You may pin to the exact commit or the version.
      # uses: seveibar/url-health-check-action@290ddd0d33480c4d52ff1893df8af480a39a8241
      uses: seveibar/url-health-check-action@v1.10
      with:
        # Target URL(s), split by |
        url: https://openhacktch9q931poi-staging.azurewebsites.net/api/healthcheck/poi
        # Number of unsuccessful attempts to call URL before giving up
        max-attempts: 1
        # Time before allowing request to time out
        request-timeout: 10s
        # Time to wait before giving up
        max-time: 1m
