name: Docker Image Build and Deploy with Swap

on:
  workflow_dispatch:
 # push:
 #  branches: [ main ]
  # pull_request:
  #  branches: [ main ]
env:
  app-name: "openhacktch9q931poi"
  rg-name: "openhacktch9q931rg"
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      # run: docker build apis/poi/web --file apis/poi/web/Dockerfile --tag my-image-name:$(date +%s)
      run: docker build apis/poi/web --file apis/poi/web/Dockerfile --tag ${{ secrets.ACR_LOGIN_SERVER }}/devopsoh/api-poi:${{ github.run_number }}
    - name: Login to the Container Registry  
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Push image
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/devopsoh/api-poi:${{ github.run_number }}
        
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Start staging slot 
      id: Start slot
      run: |
        az webapp start --name ${{ env.app-name }} --resource-group ${{ env.rg-name }} -s staging
        
    - name: Deploy to Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhacktch9q931poi'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_STAGING }}
        images: ${{ secrets.ACR_LOGIN_SERVER }}/devopsoh/api-poi:${{ github.run_number }}
        slot-name: 'staging'
        
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v2
      with:
        # Check the following URLs one by one sequentially
        url: https://openhacktch9q931poi-staging.azurewebsites.net/api/healthcheck/poi
        # Follow redirects, or just report success on 3xx status codes
        follow-redirect: false
        # Fail this action after this many failed attempts
        max-attempts: 3
        # Delay between retries
        retry-delay: 5s
        # Retry all errors, including 404. This option might trigger curl upgrade.
        retry-all: false
        
        if-no-files-found: error  # <-- last line of build job: insert below this line

  #deploy_staging:
   # needs: build
    #runs-on: ubuntu-latest
        
    - name: Swap staging slot into production
      id: slot_swap
      run: |
        az webapp deployment slot swap -g ${{ env.rg-name }} -n ${{ env.app-name }} -s staging
        url=$(az webapp show -g ${{ env.rg-name }} -n ${{ env.app-name }} --query "defaultHostName" -o tsv)
        echo "::set-output name=url::http://$url"
        
    - name: Start staging slot 
      id: Stop slot
      run: |
        az webapp stop --name ${{ env.app-name }} --resource-group ${{ env.rg-name }} -s staging

    - name: az cli logout
      run: az logout
