name: .NET

on: 
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: apis/poi/**
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Show working directory
      run: tree
    - name: Change to POI Directory
      run: cd apis/poi
    - name: Restore dependencies
      run: dotnet restore apis/poi/poi.sln
    - name: Build
      run: dotnet build apis/poi/poi.sln --no-restore
    - name: Test
      run: dotnet test apis/poi/poi.sln --no-build --verbosity normal
