name: .NET

on: 
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: apis/poi/**
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Show working directory
      run: tree
    - name: Change to POI Directory
      run: cd apis/poi
    - name: Restore dependencies
      run: dotnet restore apis/poi/poi.sln
    - name: Build
      run: dotnet build apis/poi/poi.sln --no-restore
    - name: Test
      run: dotnet test apis/poi/poi.sln --no-restore
      
    - name: Create a new issue on fail
      # You may pin to the exact commit or the version.
      # uses: hettlage/open-issue@b1c3215a274690d9251db016735eb17be0bb6437
      if: ${{ failure() }}
      uses: hettlage/open-issue@v1.0.0
      with:
        # Github Token
        token: ${{ secrets.GITHUB_TOKEN }}
        # Title for the issue
        title: Build number fail ${{ GITHUB_RUN_NUMBER }}
        # Issue body
        body: test 1234
        # Issue assignees
        assignees: isamabufool

    
